# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 无比沉沦
email: anyanhu@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  本人励志成为一名优秀Web全栈工程师，现阶段略懂Web前端开发和php开发，还在学习阶段，
  希望通过写博客来总结自己的学习成果，提高自己的技能，也希望交到更多志同道合的朋友。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.hayson.top" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  JasonHugh

# Build settings
markdown: kramdown
